name: .NET Core Build with Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  checks: write

jobs:
  build:
    # use ubuntu for more build minutes
    runs-on: ubuntu-latest
    # use release mode for all steps
    env:
      config: 'Debug'

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Install dependencies
        run: |
          cd src 
          dotnet restore
      - name: Build
        run: |
          cd src 
          dotnet build --configuration $config --no-restore
      - name: Integrationtests
        run: |
          cd test-database
          docker compose up -d
          cd ..
          dotnet test -l "trx;LogFileName=integration-test-results.trx" ./src/MartenWolverineChannels.IntegrationTests/
      - name: Integration Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: .NET Integration Tests
          path: "**/integration-test-results.trx"
          reporter: dotnet-trx
          fail-on-error: true